### ISSUE TITLE
SauceNAO crashes on some images

### ISSUE THREAD

**Issue by tsunamaru** [luk1337/SauceNAO#6]
Hey there,

SauceNAO crashes on some images. Stacktrace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.luk.saucenao/com.luk.saucenao.ResultsActivity}: java.lang.NullPointerException: resultTitle must not be null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3539)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3699)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException: resultTitle must not be null
	at com.luk.saucenao.Results.<init>(Results.kt:21)
	at com.luk.saucenao.ResultsActivity.onCreate(ResultsActivity.kt:49)
	at android.app.Activity.performCreate(Activity.java:8143)
	at android.app.Activity.performCreate(Activity.java:8115)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3512)
	... 11 more
```

Device: POCO X3 Pro
Firmware: MIUI 12.5.4.0 (Android 11)
SauceNAO: 1.8 (F-Droid)
Example image: not sure it's a good idea upload it on GitHub. Let me know if you need this, I'll send via email or any other convenient way.

And thanks for such awesome project!

**Comment by luk1337** [comment]
You can send it to my email.

**Comment by tsunamaru** [comment]
Sent image to email on your GitHub profile.

**Comment by luk1337** [comment]
Looks like 8256e9856b4fdaae2f32391fa9db7db428ec5d8b fixed this issue. I'll try to release v1.9 today or tomorrow.

**Comment by tsunamaru** [comment]
Got it. Thanks again for your efforts!
